name: nutrisport
description: Aplikasi Nutrisi & Recovery Atlet

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Database lokal penyimpanan data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  timezone: ^0.9.1  

  # Notifikasi
  flutter_local_notifications: ^17.2.3

  # Grafik Progress / Tracking
  fl_chart: ^0.66.0

  # Utility format tanggal, nilai, dsb.
  intl: ^0.18.1

  # Penyimpanan data sederhana (hydration, preferences, dsb.)
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Untuk generate adapter Hive
  hive_generator: ^1.1.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true